### ISSUE TITLE
[mail_mail] [website_sales_donate] Der Eingetragene Wert "reply-to" beim email Template wird Ignoriert

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#110]
# Bug Summary
Wenn man beim Email Template mei "reply-to"eine Fixe Email Adresse eingibt wird diese überschrieben beim generieren der Email wenn z.B aus welchen anderen Gründen auch immer ein Folllower eingetragen ist beim "website_Verkaufsteam". Wie bei Pfotenhilfe aufgrund interner Informationsweiterleitung wenn eben eine Spende eingegangen ist. 

## How to Reproduce
Weitere Tests werden noch durchgeführt um gegebenefalls weiter abhängikeiten zu entdecken. 

### Current Result
Reply-to Adresse ist die Adresse der Followers bzw. eines Partners der Organisation die bei "Verkauf" hinzugefügt wurde als add as follower. 

### Expected Result
Es wäre toll wenn der Wert der beim Email Template eingegeben ist die höchste Priorität hat.
Workaround derzeit: 
Anlegen eines anderen Users der die Email Adresse hat die als "reply-to" aufscheinen soll. Hier könnte es zu dem Problem kommen das diese Email adresse schon woanders hinterlegt ist z.b die gleiche wie beim Unternehmen. Dies wäre noch kein Problem führt aber zu verwirrung. 

## Bug Source
- Instance: ```alle``` 

# Additional Information (optional)

**Comment by michaelkarrer81** [comment]
I do agree that this would be the expected behaviour but the problem with this is that we would need to do massive testing if we change the standard e-mail behaviour in odoo.
