### ISSUE TITLE
o8r79 [auth_partner]: Token Error Message wird nicht angezeigt.

### ISSUE THREAD

**Issue by mforberich** [OpenAT/online#116]
Obwohl eine cust. defined Token Error Message bei AIAT eingegeben ist wird diese bei Eingabe eines falschen Tokens ins Formular nicht angezeigt. Bei welchem Fehlerzustand soll dies angezeigt werden?

angezeigt wird "Falscher oder abgelaufener Code!"

Mein Custom Text ist bei "Einstellungen" "Website" im Feld "apf_token_error_message" lautet 
´´´
Die Eingabe ist nicht korrekt bitte überprüfen Sie Ihre Eingabe!

Haben Sie Schwierigkeiten bei der Eingabe Ihrer Daten oder Fragen zur Absetzbarkeit Ihrer Spenden? Bitte wenden Sie sich gerne an uns: 
Tel: 01/78 00 88 (Montag bis Donnerstag 9-12 und 13-16 Uhr, Freitag 9-12 und 13-15:30 Uhr). 
E-Mail: spenden@amnesty.at

Danke für Ihre wertvolle Unterstützung!
´´´
In der Translation ist folgender Eintrag zu sehen 
"Wrong or expired code!" addons/auth_partner/fstoken_tools.py

**Comment by winston6071** [comment]
in der Version 49 war im das feld "apf_token_error_message" noch in der 
fstoken_tools.py
ab Version 50 ist es weg.

**Comment by michaelkarrer81** [comment]
Scheint schlicht im Template vergessen worden zu sein - Werde ich in den release am Mittwoch aufnehmen.
