### ISSUE TITLE
Return URL in aswidget -->  after Payment Page --> return to iframe 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#117]
# Bug Summary
actually the standard is return to /shop/confirmation_static. This is Wrong in case of aswidget integration
Correct behavior woud be that if a widgetdomain is set the return url is the whole Iframe inegration link. 
or use external link like https://www.global2000.at/danke 
SET this at "website" "donation shop" "link after paymentprovider --> does not work

## How to Reproduce
https://www.global2000.at/ich-k%C3%A4mpfe-f%C3%BCr-das-sch%C3%B6ne
click through 

### Current Result
backlink to /shop/confirmation_static --> not to this  https://www.global2000.at/danke

### Expected Result
backlink after payment provider should be in widget mode to the widget  

## Bug Source
- Instance: ```gl2k``` 
- release: ```o8r62``` 

# Additional Information (optional)
return url 
2017-08-21 13:03:29,966 27108 INFO gl2k werkzeug: 192.168.37.113 - - [21/Aug/2017 13:03:29] "GET /shop/confirmation_static?&order_id=148 HTTP/1.0" 200 -

**Comment by winston6071** [comment]
This came up at test for the first real produkt at gl2k ... test was done with EINZUG 
Do further tests now with other payment methods and create category and use return url there

**Comment by winston6071** [comment]
Test2: 
erstellen einer kategorie und zuweisen dieser zum Produkt und dort den Iframe als return Url setzen. 
STATUS: derzeit keine Auswirkung da festgestellt wurde das Global keinen aswidget eintrag beim Manager gemacht haben und einen alten link verwendet haben somit ist die Iframe ID die falsche. 

FESTGESTELLT: 
für den Returnurl 
FEHLER: 
```https://www.global2000.at/ich-k%C3%A4mpfe-f%C3%BCr-das-sch%C3%B6ne?fso_iframe=%2Fshop%2Fconfirmation_static&order_id=147```
 funktioniert es nicht wenn mn die KLASSE nimmt 
FUNKTIONIERT: 
```https://www.global2000.at/ich-k%C3%A4mpfe-f%C3%BCr-das-sch%C3%B6ne?fso_if13=%2Fshop%2Fconfirmation_static&order_id=147```
folglich MUSS man die ID des Iframes verwenden für die Iframe integrationsseite direkt aufruf der confirmation page als beispiel kann nicht die klasse "fso_iframe" verwendet werden.

**Comment by michaelkarrer81** [comment]
Closed
