### ISSUE TITLE
FS Partner token: wrong number of checks

### ISSUE THREAD

**Issue by mforberich** [OpenAT/online#123]
# Bug Summary
The "Number of checks" field always shows a minimum of 4 checks after the first use of the token

## How to Reproduce
1. Chose 12 digit token that has not been used before (Number of checks=0)
2. Use token in auth partner form and save changes
3. Check token in Odoo

### Current Result
Number of checks = 4

### Expected Result
Number of checks = 1

## Bug Source
- Instance: AIAT

**Comment by michaelkarrer81** [comment]
"Number of Checks" beschreibt die tatsächliche Anzahl der Überprüfung des Tokens im System und kann nicht mit "Number of usages" also der Anzahl der tatsächlichen Eingabe des Tokens gleichgesetzt werden.

Tatsächlich wird der Token vier mal überprüft nach der Eingabe des Tokens bis die Form mit den Finalen Daten angezeigt werden kann. Auch bei jeder weiteren Formübermittlung (Anpassung der Daten) wird der Token zusammen mit den Daten ebenfalls gesendet und überprüft (er könnte ja in der Zwischenzeit abgelaufen sein).

Daher ist "Number of Check" korrekt.

Wenn wir weitere Informationen zu Token benötigen sollten und deren Verwendung benötigen sollten wir dies gemeinsam besprechen. 

Vor allem die Fragen die mit den gewonnenen Daten beantwortet werden sollen bzw. ob diese relevant für Selektionen, Fehlersuche oder der Bewertung von Aktionen sind sollten geklärt werden bevor wir dies Anpassen. (z.B.: ist es wirklich wichtig zu wissen wie oft ein Token eingegeben wird oder wäre es wichtiger zu sehen welche Aktionen "eingeloggt" mit diesem Token durchgeführt wurden?)

@mforberich Ich würde dich bitten diesbezüglich deine Ideen und Anforderungen in einem neuen Issue zusammenzutragen und einen Termin zu vereinbaren in denen wir dies gemeinsam besprechen und dann die Ausführung planen.
