### ISSUE TITLE
Erweiterung der Mehrfachtreffer-Abfrage um 2. Vornamen

### ISSUE THREAD

**Issue by mforberich** [OpenAT/online#124]
Zur bPK Bestimmung ist so vorzugehen, dass nur mit dem 1. Vornamen gesucht wird und nur im Falle eines Mehrfachtreffers mit einem 2. Vornamen die Unterscheidung der NICHT-Eindeutigen Treffern (eigens gekennzeichnet in der Ergebnisdatei 4.3.2.3 NICHT_EINDEUTIG Datei) zu suchen. Da das Geburtsdatum zwingend anzugeben ist, ist dies nur bei sehr häufigen Namen der Fall, dass 2 Personen den gleichen Namen und auch gleichzeitig dasselbe Geburtsdatum haben. Dies kann natürlich bei besonders häufigen Familiennamen, Vornamenskombinationen (Maria, Anna, Karl, Franz, etc…… Gruber, Maier, …..) durchaus vorkommen. 

Genaues Bsp. : 
![image](https://user-images.githubusercontent.com/25081682/30869030-79855bc0-a2e0-11e7-8318-d4f49f001163.png)

![image](https://user-images.githubusercontent.com/25081682/30869059-8dac906e-a2e0-11e7-87a7-bddb150a3805.png)
![image](https://user-images.githubusercontent.com/25081682/30869087-9b138398-a2e0-11e7-8b51-f70eec553a78.png)
![image](https://user-images.githubusercontent.com/25081682/30869102-a46b7dba-a2e0-11e7-9c6d-aa9c12849ae5.png)

Wenn also das Letztergebnis ein Mehrfachtreffer ist sollte noch einmal mit den gesamten Vornamenfeldern abgefragt werden. Genau Entscheidungsbaum wäre noch zu diskutieren.

**Comment by michaelkarrer81** [comment]
Vielen Dank für die genaue Beschreibung!

**Comment by mforberich** [comment]
Hab ich nur aus Schnittstellen-Doku rauskopiert, also keine große Leistung von mir ;-) 
Meine Gedanke dazu ist, dass wir bei Mehrfachtreffer als letzten Abfragestep einfach das gesamte Vornamenfeld (bzw. natürlich Vornamenerzwungen-Feld) ohne Anpassungen schicken. So hat man dann indirekt auch die volle Kontrolle was man in das Feld schreibt und somit an das ZMR-IFC schickt. 

Lg, 
Marcus
