### ISSUE TITLE
Google Analytics Anpassung anonymize IP

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#135]
Es wäre zu erweitern 

Im Modul website/views/website_templates.xml

            <t t-call-assets="web.assets_common" t-css="false"/>
            <t t-call-assets="website.assets_frontend" t-css="false"/>
            <script t-if="website and website.google_analytics_key">
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                ga('create', _.str.trim('<t t-esc="website.google_analytics_key"/>'), 'auto');
                ga('send','pageview');
            </script>
        </body>
    </html>
</template>

hinzufügen von

ga('set', anonymizeIp', true);

**Comment by michaelkarrer81** [comment]
<script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', _.str.trim('1234567'), 'auto');
            ga('set', 'anonymizeIp', true);
            ga('send','pageview');
</script>
