### ISSUE TITLE
BIC Feld Ausblenden

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#137]
# Bug Summary
ONE PAGE CHECKOUT TEST 
If you disable BIC Field via CSS and click on next you get forwarded to the page which shows the info that you gonna be directed to the payment provider within this page the IBAN BIC gets displayed again or at least the labels. But BIC is set to RED x and the page do not forward automaticaly 

## How to Reproduce
*Example text 1:*
1. Open Browser Chrome
2. Go to Page https://www.care.at/spenden/online-spenden/
3. Disable BIC Display: none; 
3. Enter Data and hit button "Jetzt Spenden"
4. next page stucks because BIC is marked red as needed 

### Current Result
The page ```https://www.care.at/spenden/online-spenden/``` next page is opened and the paymentprovider forward page stucks.

### Expected Result
Data is updated and redirection to Thank you Page with correct information.

## Bug Source
- Instance: ```care``` o8r168
- Record/Model: 
- Reported by: testvn120318 testnm120318
- Reported at: 

# Additional Information (optional)
Direkt auf der OnePageCheckout Spendenseite 
IM CSS 
#aq7 > div:nth-child(6) {
  visibility: hidden;
}
Dann geht auch diese Seite nicht weiter da scheint dann JS zu überprüfen 

#aq7 > div:nth-child(6) {
  display: none;
}
Dann geht es durch hängt dann aber auf der nächsten Seite da ja Serverseitig der Check ausgebaut wurde

**Comment by michaelkarrer81** [comment]
Done :)
