### ISSUE TITLE
Modal Boxes in i-Frames (aswidget) can open off-screen

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/online#23]
Ich you open a modal box in a website that is displayed in an iframe the modal box will start at the top of the i-frame which may be off screen:

![bildschirmfoto 2016-06-21 um 10 19 19](https://cloud.githubusercontent.com/assets/6480630/16222675/a747865e-3799-11e6-83e4-676106f930fa.png)

http://stackoverflow.com/questions/2773669/positioning-a-jquery-dialog-that-is-inside-an-iframe-realtive-to-the-parent-wind

**Comment by winston6071** [comment]
Da von Seiten Fundoffice dieses Thema wieder aufgeworfen wurde müssten wir da mal schaun ob das Lösbar ist. 
http://stackoverflow.com/questions/24805274/bootstrap-modal-at-top-of-iframe-regardless-of-scroll-position-how-do-i-positio

**Comment by michaelkarrer81** [comment]
@winston6071 soweit ich weis wurde das per css gelöst - falls nicht bitte issue wieder öffnen.
