### ISSUE TITLE
Responsive Design Problem wenn langer text am button verwendet wird

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#26]
Wir sollten in unser Standard CSS folgendes mitaufnehmen sollte so wie bei Pfotenhilfe wieder jemand auf die Idee kommt und auf einem Button einen Langen Text schreibt. 

Dann würde zumindest die Seite korrekt dargestellt werden und nicht wie im Falle von langem text der Button die max breite der skalierung definieren. derzeit ist bei buttons white-space: nowrap; im standard gesetzt. 

    @media (max-width: 500px) {
      .btn {
        white-space: normal;
      }
    }

**Comment by michaelkarrer81** [comment]
dies kann muss aber nicht gewünscht sein und ist daher individuell pro kunde zu setzen oder eben ändern wenn der default nicht ok ist
