### ISSUE TITLE
suggested donation-values funktioniert nicht wenn ein text bei name eingegeben wird

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#27]
Test: 
Verkauf / Produkt / einstellen von 3 werten OHNE NAME TEXT bei "suggested Donation-Value" --> klick auf der Spendenseite der Buttons --> preis wird übernommen ins price feld. 

Verkauf / Produkt / einstellen von 3 werten MIT NAME TEXT bei "suggested Donation-Value" --> klick auf der Spendenseite der Buttons --> preis wird nicht mehr ins price feld übernommen.

beim herauslöschen des textes und speichern bleibt der eintrag false und es geht immer nocht nicht 
beim löschen der translation dazu geht es dann wieder, kein problem für uns wenn es einem kunden passiert unschönes handling und ist eine fehlerquelle

**Comment by michaelkarrer81** [comment]
erledigt in o8r34
