### ISSUE TITLE
website_popup test enable works only when date is valid

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#31]
nur wenn das Start Datum gesetzt ist und größer - gleich dem aktuellen Datum ist funktioniert die testfunktion /website_popup/enable

wäre kein start datum gesetzt oder kleiner aktuelles datum,  könnte man es mit der Adresse /website_popup/enable so nicht testen bzw. wird das popup nicht eingeblendet im log 303

**Comment by michaelkarrer81** [comment]
Dies ist eine gute Beobachtung jedoch denke ich nicht das ich an diesem Verhalten etwas ändern werde ? Falls es doch wichtig ist bitte wieder öffnen und einen Screenshot machen und das gewünschte Verhalten beschreiben.
