### ISSUE TITLE
Automatischer Abschluss von kostenlosen Bestellungen ohne Payment Methode

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#33]

**Comment by winston6071** [comment]
Es soll kein Zahlungsschritt kommen 
nicht bei One Page 
nicht bei Step by Step 
Ausser es würde eine Spende zusätzlich gemacht werden dann müsste die Zahlungsmethode trotzdem angezeigt werden.

**Comment by michaelkarrer81** [comment]
Done
