### ISSUE TITLE
Sperren von einzelnen websites 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#34]
kurz mit mike besprechen
fund -->  https://www.odoo.com/apps/modules/8.0/website_security/

**Comment by winston6071** [comment]
Anlassfall Google Suchergebnis aiwwf --> zweite seite im google findet 
https://www.google.at/url?sa=t&rct=j&q=&esrc=s&source=web&cd=11&cad=rja&uact=8&ved=0ahUKEwj33YalgYrPAhUD0xoKHRUrCmo4ChAWCBswAA&url=http%3A%2F%2Fwww.datadialog.net%2Fforum%2Fentwicklerforum-2%2Ftag%2Faiwwf-100200%2Fquestions&usg=AFQjCNHKeRiqLcAb9blPjzou7ISrqvPgaw&sig2=H3f4qv71WAxZ-hsw_hyunQ&bvm=bv.132479545,d.bGs

damit ist das interne forum erreichbar.

**Comment by winston6071** [comment]
derzeitige Lösung:
im cu_dadi modul website_dd hinzufügen von robots.txt 
im google webmaster tools url entfernen und die url löschen lassen check morgen ob das entfernt wurde. 

OFFEN: SPERRE des INTERNEN FORUMS ....

**Comment by michaelkarrer81** [comment]
Hier sehe ich keine andere Lösung als die robots.txt zu verbessern. 

Bei einem Direktzugriff auf unsere internes Forum kommt 403 wenn man nicht angemeldet ist - sollte also passen? Bitte wieder öffnen falls man auf ein geschütztes Forum zugreifen kann.
