### ISSUE TITLE
Das laden des Spendenformulars bei care dauert sehr lange

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#35]
Test: Laden der website https://www.care.at 
klick: Spenden 
klick: Online Spenden
Seite ist geladen bis zum Dropdown der Spendenauswahl dann ladet die Seite nach 2 - 3 Sekunden kommt das Spendenformular

Test2: Aufruf von care.datadialog.net direkt und test 
Aufruf: http://care.datadialog.net/shop/product/online-spende-22
Seite Erscheint SOFORT Ladezeit aber trotzdem 1,7 Sekunden für JS 
Auswirkung dann offensichtlich nur beim aswidget 

Test2: Test über Pingdom direkt mit http://care.datadialog.net/shop/product/online-spende-22
dauer ca. 2.02 Sekunden davon 1,45 Sekunden wait 

https://gtmetrix.com/reports/www.care.at/iWSWTntN

https://tools.pingdom.com/#!/dD9Na0/https://www.care.at/spenden/online-spenden/

![care_12sept-performanceinfo](https://cloud.githubusercontent.com/assets/5407843/18439422/95977600-7905-11e6-8168-a0ef486d6373.jpg)

**Comment by winston6071** [comment]
weiterführendes 

Nach einer erneuten Analyse über das devtool von chrome sind diese waits genauer betrachtet gaps wo nichts passiert kein request stattfindet. 
weiterführende literatur problemfall 

http://stackoverflow.com/questions/4991167/gaps-in-firebug-waterfall-chart?rq=1

http://www.softwareishard.com/blog/firebug/firebug-net-panel-timings/

hier ist ersichtlich das von 1,7 sekunden "others" --> zumindest im groben schon mal 1,4 sec auf das konto von "kein request, nichts" geht. 

![developer_tools_-_http___bsvw_datadialog_net_bsvw_config_static_src_bsvw_iframe_bsvw_iframe_htm_debug](https://cloud.githubusercontent.com/assets/5407843/18660489/03638d84-7f11-11e6-9396-9c327ce2812c.jpg)

bei care ist nach dem laden des letzen bildes onlinespende_hilfe_allgemein.jpg ca. 1,1 sekunden nichts bis dann receive Response kommt von shop.care.at onlinespende-22 
![developer_tools_-_https___www_care_at_spenden_online-spenden_](https://cloud.githubusercontent.com/assets/5407843/18661389/d62d188a-7f15-11e6-9127-ff096a53f347.jpg)

**Comment by michaelkarrer81** [comment]
@winston6071 Könntest du bitte hier bei Care erneut nachfragen ob das noch ein Thema ist oder nicht? Wenn nicht bitte Bug schließen. 

Falls es doch noch ein Problem ist bitte Zeitmessungen von einem Aufruf des widgets in einer unserer Seite anlegen damit wir herausfinden ob es am Java Script der Care Seite liegt (also am Code vom Flo)
