### ISSUE TITLE
Kostenlos & Varianten mit Preis - keine Summe im Price feld

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#37]
aufgefallen ist es mir bei der Suche nach der Optimalen Lösung für die Mitgliedschaften 
1. Hat man ein Produkt angelegt mit 0 EUR dann wird im Preis Feld nichts angezeigt auf wenn man Varianten hat die dann ein + bewirken sollten
2. Hat man ein Produkt angelegt mit Standard 40 EUR  und varianten so wird derzeit bei der Wahl der Variante der Produktpreis im Feld drunter nicht Aktualisiert

--------------------- weiterführende Info ---------------- 
bei einer Mitgliedschaft bietet es sich an ein Kostenloses Produkt anzulegen mit Varianten
z.B: 
Standard: 40 EUR 
Schüler: 20 EUR 
Förderer: 400 EUR 
usw...

dies ist derzeit nicht möglich

derzeitiger Workaround: bzw. eigentlich sogar die schönere Variante 
für jede Mitgliedschaft ein eigenes Produkt anlegen mit der gleichen FSGroup ID 
und anlegen einer

**Comment by michaelkarrer81** [comment]
@winston6071 Hab hier die Anforderung noch nicht wirklich verstanden. Wenn dies noch aktuell ist bitte eine Besprechung für diese Erweiterung ansetzten in der du mir zeigst was du gerne umsetzen möchtest.

**Comment by michaelkarrer81** [comment]
@winston6071 please check and close or explain to me :)

**Comment by winston6071** [comment]
Varianten werden von unserem System noch nicht supported. damit ende

Da die Mitgliedschaften für Birdlife nun so gehandelt werden wie eingestellt und oben erklärt erübrigt sich die Varianten Thematik. 

Varianten wären sicherlich ein Extra zu besprechendes Thema um neue Spendenoptionen die andere noch nicht so anbieten auf den Markt zu bringen .... 

Ideen: 
Kostenlose Kataloge mit einer Mini Spendenoption 
Mitgliedschaften mit Varianten zur Auswahl 
müsste man sich genau durchüberlegen was hier ginge.
