### ISSUE TITLE
Simple checkout aktiviert bei Produkt mit wiederkehrender Zahlungsmethode "jährlich" Methoden werden nicht eingeschränkt 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#39]
Master und VISA und PAYPAL und SOFORT werden zusätzlich zu SEPA bzw. Zahlschein angezeigt

**Comment by michaelkarrer81** [comment]
@winston6071 ist dieser Bug noch present, kann ihn nicht reproduzieren? - Wenn ja müssten wir den ja schnellsten lösen?!?

Bitte testen und gegebenenfalls schließen oder Screenshots anfügen!

**Comment by michaelkarrer81** [comment]
@winston6071 please check today :)

**Comment by winston6071** [comment]
Test in der Version o8r97 scheint bereits behoben
