### ISSUE TITLE
Additional css classes for the checkout box with OPC

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#4]
nice to have JETZT nicht so wichtig: 
- CSS Class unterschied beim Formular:

checkout title, hat class 
payment_method keine 
wäre schöne wenn alle bereiche gleich funktionieren ist aber nicht wichtig 

mit first child gehts 

.checkout_title,
# payment_method .col-lg-12:first-child {

  background: $careyellow;

"Shipping" Überschrift hat keine klasse für die Überschrift

**Comment by michaelkarrer81** [comment]
Not now :)
