### ISSUE TITLE
error partner_name bei Kontaktformular wenn über das Menü "Anpassen" "company name" ausgeblendet wird

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#42]
auf der Seite 
http://www.pfotenhilfe.org/page/website.contactus
Test1:
"Anpassen" deaktivieren "company name" 
ausfüllen absenden --> ERROR partner_name

Test2: 
"Anpassen" aktivieren von "company name" 
auf der Form eingeblendet und NICHT ausgefüllt abgesendet alles OK 

Test3: 
auf der Alternativen Spendenformular Snippet
ausgeblendet mittels CSS 
http://www.pfotenhilfe.org/page/kalender-2017
kann abgesendet werden ohne "partner_name" Fehler

**Comment by michaelkarrer81** [comment]
@winston6071 Bitte Testen ob der Fehler noch auftritt. Wenn wie erwartet nicht bitte Issue schließen.
