### ISSUE TITLE
Use the new field birthdate_web also for checkout and billing fields with german format

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/online#58]
ToDo:

  - [x] Correctly render fields of type Date in german format
  - [x] Update the default fields of billing and checkout fields to include birthdate_web with correct frontend validation instead of the current birthdate field
 - [ ] @winston6071 Update all existing instances (manually)

**Comment by winston6071** [comment]
Wenn ich das " BIrthdate web" verende am normalen Checkoutformular dann stimmt etwas mit der validierung nicht.... eingabe 01.01.1977 kommt immer ein X

**Comment by michaelkarrer81** [comment]
Done
