### ISSUE TITLE
Checks warum so viele Sales Orders angelegt werden und ob man da was verbessern könnte

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#59]
gecheckt bei care pgadmin sales.order 
ID 27869 Verursachte im log das serialization update .... problem 
2 einträge zuvor war eine erfolgreiche Spende 
check die ID die beim shipping partner hinterlegt ist 63342 bei der guten ... und immer 4 bei einem shop view ... bzw. auch bei dem fehler .... sofern die ID die Sales Order ID ist....

**Comment by michaelkarrer81** [comment]
Verstehe hier die Anfrage nicht ganz. Das viele Sales Order angelegt werden liegt an One Page Checkout wo ich bereits eine SO anlegen muss wenn der User nur eine Produktseite mit OPC aufmacht da ich ja bereits das Produkt in den Warenkorb lege. 

Das Problem das du beschreibst scheint ja was anderes zu sein ?!? Da ich das nicht nachvollziehen kann schließe ich den Bug erstmal.
