### ISSUE TITLE
Neuer Paymentprovider "Zahlschein"

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#61]
Kostenlose Produkte damit abschließen 
Gleichzeitig es ermöglichen einen Zahlschein über Online zu bestellen mit angabe IBAN BIC 
Sofort lösbar mit duplizierung des Methode WIRELESS --> ohne Angebe IBAN BIC 
Mit Angabe IBAN BIC --> Prozess im Fundraising Studio ???

Oberfläche: 
Wann wird es ein oder ausgeblendet ?

**Comment by michaelkarrer81** [comment]
Die Funktion "Automatischer Abschluss von kostenlosen Bestellungen" ist eine eigenen Funktion und sollte mit dem Payment Provider "Zahlschein" nicht zusammen hängen. See #67
