### ISSUE TITLE
aswidget domain redirect forwards even no entry is made for a second domain

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#63]
beispiel:
im DNS gibt es spenden.projuventute.at und responsivespenden.projuventute.at 
beide zeigen auf unseren gateway webserver 

spenden.projuvnetute.at ist eingetragen als aswidget domain --> forward OK 
responsivespenden.projuventute.at ist nicht eingetragen bei aswidget domains --> trotzdem forward auf die hauptdomain welche schon beim ersten eintrag in dieser Tabelle gemacht wurde.

Es scheint als würde nur abgefragt ob aswidget domain gesetzt ist oder nicht. Für die erweiterte Funktionalität das wir einen Landingpage haben wollen obwohl aswidget konfiguriert ist müsste diese Funktion erweitert werden bzw. gecheckt woran es liegt.

**Comment by michaelkarrer81** [comment]
Hallo Joe,

nach der Analyse des codes würde ich sagen das dieser im Grunde ok war jedoch nur genau diesen hier durch Zufall erzeugten Sonderfall nicht abdeckt:

Der Code lautet:

``` if domain.aswidget_domain and domain.aswidget_domain in base_url:```

in unserem konkreten Beispiel:

```if spenden.projuvnetute.at and  spenden.projuvnetute.at in responsivespenden.projuventute.at```

jetzt steckt ja tatsächlich **spenden.projuventute.at** komplett in **responsive*spenden.projuventute.at*** - Ein Sonderfall der mit einer anderen Wahl des Subdomainnamens leicht verhindert werden könnte.

Eine Lösung wäre das ich statt ```in``` auf ```==``` umstelle was das Feature "Einen Eintrag für alle Subdomains" nehmen würde. Ich warte mal bis du Mittwoch wieder da bist dann können wir die Für und Wieders schnell durchgehen und das entscheiden.
