### ISSUE TITLE
Checkbox Untersagung Spendenabsetzbarkeit wird nicht entfernt

### ISSUE THREAD

**Issue by mforberich** [OpenAT/online#66]
Step 1: SPAK-Formular aufrufen und Code von neuem Testdatensatz eingeben.
Step 2: Haken setzen bei Checkbox "Spenden nicht absetzen" und Formular absenden
Check in FRST: Gruppe "Untersagung Datenübermittlung Finanzamt" ist jetzt gültig
Step 3: Aus Formular ausloggen und nochmals mit gleichem Code einloggen.
Check in Formular: Checkbox  "Spenden nicht absetzen" ist angehakt
Stepf 4: Haken entfernen und Formular absenden
Expected Result: In FRST ist Gruppe wieder ungültig gesetzt (es ist aber erkennbar dass sie für einen gewissen Zeitraum aktiv war)
Actual Result: Gruppe ist in FRST noch immer aktiv

**Comment by michaelkarrer81** [comment]
Danke für die Info!

Hab den Bug zum sosyncer verschoben:
[sosync Issue 15](https://github.com/OpenAT/sosync/issues/15)
