### ISSUE TITLE
Spenden "Aufträge" rootcateg. nicht angezeigt in einem Fall 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#71]
Bei Care:
selten aber ab und zu fehlt in der "Aufträge Liste" die "Rootcat." hinten … nur dann …. wenn offensichtlich 2 verschiedene Kategorien ausgewählt werden wie z.b schenkenMitSinn also bei Care  was vom „shop“ bestellt "schenkenmitsinn" kategorie .....
 und dann noch wo anders geklickt auf "Online Spenden" z.b
--> 3 Zeilen in der Sales Order wo diese beiden KAtegorien verwendet sind dann ist die Kategorie leer
hat man aber z.b 3 oder x mal mal was aus SchenkenMitSinn dann ist die RootKategoier sauber ausgefüllt … nur "OnlineSpenden" ebenso alles gut 

weitere tests:
check alle Konfigurationssettings der Produkte und Kategorien ob das durch config zustande gekommen ist. 

DIESE Info hat nichts mit dem Upate o8r53 zu tun … ist generell zumindest derzeit in der CARE Datenbank da gerade sehr genau getestet wird

**Comment by michaelkarrer81** [comment]
Ist leider so und kann nicht immer ausgeschlossen werden
