### ISSUE TITLE
[widget_manager] Fehlermeldung bei sourcepage auswahl "kann nicht finden"

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#80]
Wenn man bei der Sourcepage die Kategorie mitangeben möchte 
so kommt eine Fehlermeldung das er den link nicht finden kann. 

das geht
/shop/product/leben-retten-14
das geht nicht 
/shop/product/leben-retten-14**?category=2**

somit stimmt auch der Iframe code nicht der dann in weiterer folge überprüft werden würde wenn man den link korrigiert. 

bei care ergibt sich dadurch ausserdem das die JS Seite welche bei Care implementiert ist 
3 mal auf das gleiche Target Url verweist. 

Beispiel: 
siehe Attachement
![widget_manager_-_odoo_care](https://cloud.githubusercontent.com/assets/5407843/25388126/348dae0a-29cd-11e7-94ca-3a57a7f0dc02.jpg)

**Comment by michaelkarrer81** [comment]
Done
