### ISSUE TITLE
[website_pfoh] Add Zip Code into contact Form and take over into res.partner too

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#93]
# Extention Summary
Adding ZipCode in contactus_form 

## How to Reproduce
http://www.pfotenhilfe.org/page/contactus_form

*Example text 2:*

### Current Result
no Zip code is displayed at all. 
Test inside local Modul but no new Branch created the moment --> Zipcode is added only inside Email content but not inside res.partner realted fields 
pfot/update/pfot_update/addons/website_pfoh/views/contact_form.xml
```
        <!-- add "Zip" to fields in contact form -->
        <template id="pfot_contactus_form" inherit_id="website_crm.contactus_form" name="pfot custom contactus_form modifications ZIP" customize_show="True" active="False">
            <xpath expr="//div[./div/input[@name='name']]" position="after">
                <div t-attf-class="form-group #{error and 'zipcode' in error and 'has-error' or ''}">
                    <label class="col-md-3 col-sm-4 control-label" for="zipcode">Zip</label>
                    <div class="col-md-7 col-sm-8">
                        <input type="text" class="form-control" name="zipcode" t-attf-value="#{zipcode or dict(kwargs).get('zipcode', '')}"/>
                    </div>
                </div>
            </xpath>
        </template>
```
### Expected Result
Data should be included in the corresponding fields from res.partner too so zip code should be written into zip too. 

## Bug Source
- Instance: ```online_o8r60``` 
- Record/Model: res.partner, website_crm.contactus_form
- Reported by: Joe Grubelnik
- Reported at: 29.05.2017

# Additional Information (optional)
Interesting found inside existing OCA Modules 
/online_o8r60/addons-thirdparty/oca/website/setup/website_crm_address/odoo_addons/website_crm_address/views/contactus_form.xml

**Comment by michaelkarrer81** [comment]
Done
