### ISSUE TITLE
[payment_transfer] Zahlschein VIA WireTransfer should redirect to confirmation_static

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#94]
# Bug Summary
Zahlschein Via Wiretransfer Test for Mike:
at the moment after payment the /shop/confirmation is called and not /shop/confirmation_static

## How to Reproduce
*just do a normal donation with "zahlschein" as Wiretransfer Paymentprovider 1:*
0. Duplicate "Wire Transfer" --> rename to "zahlschein" 
1. donate
2. fill out checkout data
3. choose "paymentmethod" 
4. klick "jetzt spenden"

*Example text 2:*

### Current Result
 --> redirect to http://127.0.0.1:8069/shop/confirmation

### Expected Result
 --> redirect to http://127.0.0.1:8069/shop/confirmation_static 

## Bug Source
- Instance: ```online_o8r60``` 
- Record/Model: payment_transfer/models/payment_acquirer.py
- Reported by: Joe Grubelnik
- Reported at: 29.05.2017

# Additional Information (optional)
Workaroud tests: 
1.
Configure a new Pubplic Group and duplicate an existing Product to use this Category and SET the redirect after paymentpage to http://127.0.0.1:8069/shop/confirmation_static --> has no impact
2.
Configure redirect at Paymentprovider itself "redirect_after_form_feedback" --> has no impact 
on both configurations it stays at /shop/confirmation

**Comment by michaelkarrer81** [comment]
Done
