### ISSUE TITLE
[fso_con_zmr] different results in FS and FSO

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/online#98]
# Bug Summary
Different results in FS and FSO with same donor data.

## How to Reproduce
Firstname: Gertrud 
Lastname: Maier 
Birthdate: 30.07.1939 
plz: 9312

Eva Maria Müller 09.11.1955 PLZ 2103

### Current Result
in FS: Multiple person matched
in FSO: No person matched

## TODO:

- [ ] Check if FS uses the correct xmlrpc function 
- [ ] Check why only year is used for last request for person Gertrud Maier - Full Birthdate is expected
- [ ] Marcus will ask if we can send all available data already on the first request or if it is really needed to do the request multiple times based on each request answer

**Comment by kaipm** [comment]
FS user interface does not provide the PLZ field as of yet, which is likely why ZMR hits multiple records. Will verify tomorrow.

The fix would be easy in that case, but I'll need the definition of which address to pick in case there are multiple valid addresses.

**Comment by michaelkarrer81** [comment]
Closing this issue because the reason was just the missing "zip" number ;)
